version: '3.7'

services:
  mysqldb:
    image: mysql:9.0.0
    restart: always
    # ports:
    #   - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=todolist
    networks:
      - backend-network
  server:
    build: ./server
    restart: always
    # ports:
    #   - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/todolist
      - spring.datasource.username=user
      - spring.datasource.password=password
      - spring.stompbroker.url=ws://rabbitmq:15674/ws
    depends_on:
      - mysqldb
    networks:
      - backend-network
  frontend:
    build: ./web
    # ports:
    #   - "3000:3000"
    networks:
      - backend-network
  nginx:
    build: ./proxy
    ports:
      - "80:80"
    networks:
      - backend-network
  rabbitmq:
    build:
      dockerfile: ./dockerfile.rabbitmq
    # ports:
    #   - "15672:15672" # web management plugin
    #   - "15674:15674"
    networks:
      - backend-network
networks:
  backend-network:
